import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useState} from 'react'
import Timer from '../../components/preset/presA01/Timer'
import Gallery from '../../components/preset/presA01/Gallery'
import { FaAngleDoubleDown,FaRegEnvelopeOpen, FaInstagram, 
        FaSearchLocation, FaRegCopy, FaHeart, FaCalendarAlt
        ,FaImages, FaGift } from "react-icons/fa"


function PresA01() {

    const router = useRouter()
    const { to } = router.query
    const [topPosition, setTopPosition] = useState(0)

    const moveUp = () => {
        setTopPosition(topPosition - 1000);
    }

    const images = [
        { src: '/images/preset/A01/gallery-1.jpg', alt: 'First' },
        { src: '/images/preset/A01/gallery-2.jpg', alt: 'First' },
        { src: '/images/preset/A01/gallery-3.jpg', alt: 'First' },
        { src: '/images/preset/A01/gallery-4.jpg', alt: 'First' },  
    ]

    useEffect(()=>{
        const fadeUpElements = document.querySelectorAll(".fadeUp");
        // Loop melalui setiap elemen
        fadeUpElements.forEach((element) => {
            console.log("looped");
        // Animasi awal saat halaman dimuat
        gsap.set(element, {
            y: 80, // Pindahkan elemen 100px ke bawah
            opacity: 0, // Set opasitas menjadi 0
        });

        // Animasi saat ScrollTrigger mencapai elemen
        ScrollTrigger.create({
            trigger: element,
            start: "top 90%", // Trigger ketika elemen di-scroll masuk 80% ke dalam viewport
            toggleActions: "play", // Mainkan animasi saat masuk ke dalam viewport
            animation: gsap.to(element, {
            y: 0, // Kembalikan elemen ke posisi awal
            opacity: 1, // Fade elemen menjadi terlihat
            duration: 1, // Durasi animasi 1 detik
            ease: "power2.out", // Jenis easing
            }),
        });
        });
    },[])
  
    return (
        <div className=' w-full box-content text-white'>
            <Head>
                <title>Rabine.id - Preview </title>
                <meta name="description" content="Generated by create next app" />
                <meta property="og:image" content="http://contentmanagement.cendikabangsa.sch.id/wp-content/uploads/2023/09/WhatsApp-Image-2023-09-23-at-17.04.06.jpeg" />
                <meta property="og:image:width" content="400" />
                <meta property="og:image:height" content="300" />
                <link rel="icon" href="/rbn.ico" />
                <script async src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
                <script async src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
            </Head>
            <div className='w-full flex flex-row items-start justify-between'>

                {/* COVER UNDANGAN */}
                <div className='w-full h-screen fixed z-20 moving-up flex flex-col items-center justify-center' style={{ top: `${topPosition}px` }}>
                    <div className='w-full h-screen relative flex items-center justify-center'>
                        <div className='flex flex-col items-center justify-end absolute bg-gradient-to-t from-black 
                                        to-transparent via-black/75 w-full h-screen top-0 pb-20'>
                            <h1>THE WEDDING OF</h1>
                            <h1 className='font-bold text-5xl pb-8 font-Royal-Exq'>ANDRE & CITRA</h1>
                            <p className='text-sm'>Kepada Yth. Bapak/Ibu/Saudara(i)</p>
                            <h1 className='py-8 font-bold'>{to}</h1>
                            <button className='flex flex-row items-center justify-center gap-2 blink bg-white rounded-lg 
                                            text-black px-5 py-2 hover:bg-yellow-100' onClick={moveUp}>
                               <FaRegEnvelopeOpen/> Buka Undangan
                            </button>
                        </div>
                        <Image
                            src='/images/preset/A01/bg-couple.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                    </div>
                </div>

                {/* SISI KIRI (TAMPILAN PC) */}
                <div className="hidden md:flex bg-cover bg-center md:w-1/2 lg:w-[60%] h-screen overflow-hidden sticky top-0" 
                     style={{backgroundImage: "url('/images/preset/A01/bg-couple.jpg')"}}>
                    <div className='gap-y-4 w-full h-full bg-gradient-to-l from-black to-transparent flex flex-col justify-end items-end 
                                 py-12 px-10 relative'>
                        <FaAngleDoubleDown className='scroll-me font-bold text-xl '/>
                        <h1>scroll ke bawah</h1>
                        <h1 className='text-3xl font-bold text-right font-Batusa'>The Wedding Of Randy And Citra</h1>
                        <div className='flex flex-col items-center justify-center gap-y-4 bg-white/80 rounded-full 
                                    text-black top-1/2 right-8 py-5 px-2 absolute  z-50 ' >
                            <FaHeart className=" hover:text-orange-800 cursor-pointer"/>
                            <FaCalendarAlt className=" hover:text-orange-800 cursor-pointer"/>
                            <FaSearchLocation className=" hover:text-orange-800 cursor-pointer"/>
                            <FaImages className=" hover:text-orange-800 cursor-pointer"/>
                            <FaGift className=" hover:text-orange-800 cursor-pointer"/>
                        </div>
                    </div>
                </div>

                {/* SISI KANAN */}
                <div className='w-full md:w-1/2 lg:w-[40%] overflow-y-auto relative'>

                    {/* MENU NAVIGASI BAWAH */}
                    {/* <div className='md:hidden fixed bottom-0 z-10 w-full p-2 bg-white/70 text-black 
                                    flex flex-row items-center justify-center gap-x-6 rounded-t-3xl text-2xl backdrop-blur-xl'>
                        <FaHeart className=" hover:text-orange-800 cursor-pointer"/>
                        <FaCalendarAlt className=" hover:text-orange-800 cursor-pointer"/>
                        <FaSearchLocation className=" hover:text-orange-800 cursor-pointer"/>
                        <FaImages className=" hover:text-orange-800 cursor-pointer"/>
                        <FaGift className=" hover:text-orange-800 cursor-pointer"/>
                        
                    </div> */}

                    {/* OPENING_PHOTO */}
                   <div className='w-full h-screen relative'>
                        <div className='p-12 absolute top-0 bg-black/40 w-full h-full flex flex-col items-start justify-end fadeUp'>
                            <p>THE WEDDING OF</p>
                            <h1 className='font-bold text-6xl py-4 font-Royal-Exq'>ANDRE &<br/>CITRA</h1>
                            <div className='flex flex-row items-end justify-start w-full'>
                                <p className='tracking-[0.5rem]'>24.05.2024</p>
                                <div className='w-full h-[1px] bg-white'></div>
                            </div>
                        </div>
                        <Image
                            src='/images/preset/A01/couple-opening.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                   </div>

                   {/* AYAT ALQUR'AN */}
                    <div className='w-full relative bg-center bg-cover flex flex-col items-center justify-center px-16 py-[200px]'
                         style={{backgroundImage: "url('/images/preset/A01/Template-1-Marble.webp')"}}>
                         <Image
                            src='/images/preset/A01/separator-saphire.svg'
                                width={1200}
                                height={1200}
                                className='w-[5%] absolute top-10 fadeUp'
                                alt='appstore'
                        />
                         <Image
                            src='/images/preset/A01/separator-saphire.svg'
                                width={1200}
                                height={1200}
                                className='w-[5%] absolute bottom-28 fadeUp'
                                alt='appstore'
                        />
                        <p className='text-center fadeUp'>
                            “Dan diantara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, 
                            agar kamu cenderung dan merasa tenteram kepadanya dan Dia menjadikan diantaramu rasa kasih dan sayang. 
                            Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.“
                        </p>
                        <p className='text-center text-xl py-4 fadeUp'>
                            (QS. Ar-Rum ayat 21)
                        </p>
                    </div>

                   {/* QUOTES CALON PENGANTEN*/}
                     <div className='w-full  relative'>
                        <div className='p-12 absolute top-0 bg-black/80 w-full h-full flex flex-col items-center justify-between'>
                        <Image
                            src='/images/preset/A01/bg-couple.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover rounded-xl -mt-28 fadeUp'
                            alt='appstore'
                        />
                        <p className='text-center font-bold text-xl lg:text-2xl px-10 lg:px-16 font-Batusa fadeUp'>
                            Love seems the swiftest but it is the slowest of all growths. No man or woman really knows what perfect 
                            love is until they have been married a quarter of a century.
                        </p>
                        <Image
                            src='/images/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%] fadeUp'
                            alt='appstore'
                        />
                        </div>
                        <Image
                            src='/images/preset/A01/bg-section-1.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                    </div>

                     {/* MEMPELAI */}
                     <div className='w-full relative bg-center bg-cover flex flex-col items-center justify-center px-16 py-[100px] text-center'
                        style={{backgroundImage: "url('/images/preset/A01/Template-1-Marble.webp')"}}>
                        <div className='w-[14rem] h-[16rem] rounded-t-full bg-top bg-cover fadeUp'  style={{backgroundImage: "url('/images/preset/A01/bride.png')"}}></div>
                        <h1 className='font-bold text-2xl font-Royal-Exq py-6 fadeUp'>Citra Lestari Alamku</h1>
                        <Image
                            src='/images/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%] my-6 fadeUp'
                            alt='appstore'
                        />
                        <h1 className='my-8 fadeUp'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center fadeUp'>
                            <FaInstagram/>
                            citra_la
                        </div>
                        <h1 className='text-[5rem] my-10 font-Royal-Exq fadeUp'>&</h1>
                        <div className='w-[14rem] h-[16rem] rounded-t-full bg-top bg-cover fadeUp'  style={{backgroundImage: "url('/images/preset/A01/groom.png')"}}></div>
                        <h1 className='font-bold text-2xl font-Royal-Exq py-6 fadeUp'>Andre Taulanu</h1>
                        <Image
                            src='/images/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%] my-6 fadeUp'
                            alt='appstore'
                        />
                        <h1 className='my-8 fadeUp'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center fadeUp'>
                            <FaInstagram/>
                            andre_t
                        </div>
                    </div>

                    {/* INFO ACARA */}
                    <div className='w-full  relative bg-center bg-cover ' style={{backgroundImage: "url('/images/preset/A01/bg-section-2.jpg')"}}>
                        <div className='bg-gradient-to-t from-black to-black/50 via-black/80 w-full h-full  flex flex-col items-center justify-center
                                        py-20 px-12 gap-y-10 text-center'>
                            <div className='flex flex-col items-center justify-center'>
                                <h1 className='text-2xl font-Royal-Exq fadeUp'>Minggu, 24 Mei 2024</h1>
                                <Image
                                    src='/images/preset/A01/separator-sparkling.svg'
                                    width={1200}
                                    height={1200}
                                    className='object-cover w-[20%] fadeUp'
                                    alt='appstore'
                                />
                            </div>
                            <div className='flex flex-col items-center justify-center fadeUp'>
                                <h1 className='text-3xl font-Royal-Exq'>Akad Nikah</h1>
                                <p>08.00 WIB s/d Selesai</p>
                            </div>
                            <div className='flex flex-col items-center justify-center fadeUp'>
                                <h1 className='text-3xl font-Royal-Exq'>Resepsi Pernikahan</h1>
                                <p>10.00 WIB s/d Selesai</p>
                            </div>
                            <div className='flex flex-col items-center justify-center fadeUp'>
                                <h1 className='text-3xl font-Royal-Exq'>Hotel Jayakarta Bandung</h1>
                                <p>Jl. Ir. Juanda No 381A, Dago, Kecamatan Coblong, Kota Bandung, Jawa Barat</p>
                            </div>  
                        </div>
                    </div>

                    {/* COUNTDOWN */}
                    <Timer targetDate = {'2024-02-24T08:00:00Z'} anim = {{fadeUp :'fadeUp'}}/>

                    {/* GOOGLE MAP */}
                    <div className='w-full flex flex-col items-center justify-center bg-black gap-y-8'>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15799.40307219353!2d112.5761332!3d-8.1166731!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e789fe408c2880b%3A0x60b0af7bd09faf32!2snadhirdecal!5e0!3m2!1sid!2sid!4v1708078149410!5m2!1sid!2sid" 
                                className='w-full h-[500px]'
                                width="600" 
                                    height="600" 
                                    style={{border:0}} 
                                    allowfullscreen="" 
                                    loading="lazy" 
                                    referrerpolicy="no-referrer-when-downgrade">
                        </iframe>
                        <button className='flex flex-row items-center justify-center gap-2 border border-white px-5 py-2 mt-4
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out'>
                            <FaSearchLocation/> view Location
                        </button>
                    </div>

                    {/* YOUTUBE */}
                    <div className='w-full flex flex-col items-center justify-center bg-black gap-y-8 py-20'>
                        <iframe 
                            className='w-full'
                            height="315" 
                            src="https://www.youtube-nocookie.com/embed/kebq86BTZFA?si=9saOo4u4j5ry06DO" 
                            title="YouTube video player" 
                            frameborder="0" a
                            llow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                            allowfullscreen>
                        </iframe>
                    </div>

                    <Gallery images={images}/>

                    {/* GIFT */}
                    <div className='h-full  bg-black py-12 flex gap-y-8 flex-col items-center justify-center'  
                        style={{backgroundImage: "url('/images/preset/A01/Template-1-Marble.webp')"}}>
                           <h1 className='text-[2.5rem] font-Royal-Exq'>Gifts</h1>
                           <div className='w-[400px] flex rounded-lg p-8 bg-cover bg-center flex-col items-start justify-between' 
                                style={{backgroundImage: "url('/images/preset/A01/crdit_card.jpg')"}}>
                               <div className='flex flex-row items-center justify-between w-full'>
                                    <h1>Mandiri</h1>
                                    <Image
                                        src='/images/preset/A01/mandiri.webp'
                                        width={1000}
                                        height={1000}
                                        className='w-[28%] object-contain'
                                        alt='appstore'
                                    />
                               </div>
                               <Image
                                    src='/images/preset/A01/chip.png'
                                    width={1000}
                                    height={1000}
                                    className='w-[12%] object-contain my-8'
                                    alt='appstore'
                                />
                                <h1 className=' text-[1rem] text-center tracking-wider font-GameCube mb-4'>647387374648</h1>
                                <h1>Andre T</h1>
                           </div>
                           <button className='flex flex-row items-center justify-center gap-2 border border-white px-5 py-2 mt-4
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out text-sm'>
                            <FaRegCopy/> copy no rek
                        </button>
                    </div>

                    {/* CLOSING */}
                    <div className='w-full  relative'>
                        <div className='p-12 absolute top-0 bg-black/40 w-full h-full flex flex-col items-start justify-end'>
                            <p>Two souls become one, two hearts beat as one</p>
                            <h1 className='font-bold text-6xl py-4 font-Royal-Exq'>ANDRE &<br/>CITRA</h1>
                            <div className='flex flex-row items-end justify-start w-full'>
                                <p className='w-1/3'>Thank You</p>
                                <div className='w-2/3 h-[1px] bg-white'></div>
                            </div>
                        </div>
                        <Image
                            src='/images/preset/A01/bg-closing.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                   </div>

                </div>
            </div>
        </div>
    )
}

export default PresA01
