import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useRouter } from 'next/router'

import { FaAngleDoubleDown } from "react-icons/fa"

function presA01() {
  return (
    <div className=' w-full'>
        <Head>
            <title>Rabine.id - Preview </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/rbn.ico" />
        </Head>
        <div className='w-full flex flex-row items-start justify-between'>
            <div className="bg-cover bg-center w-2/3 h-screen overflow-hidden sticky top-0 " style={{backgroundImage: "url('/img/preset/A01/bg-couple.jpg')"}}>
                <div className='w-full h-full bg-gradient-to-l from-black to-transparent flex flex-col justify-end items-end text-white py-12 px-10'>
                <FaAngleDoubleDown className={`scroll-me`}/>
                    <h1>Scroll Kebawah</h1>
                    <h1 className='text-3xl font-bold'>The Wedding Of Randy And Citra</h1>
                </div>
            </div>
            <div className=' w-1/3 h-[1200px] overflow-y-auto'>
                this
            </div>
        </div>
    </div>
  )
}

export default presA01