import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect,useRef } from 'react'
import { useRouter } from 'next/router'
import { useState} from 'react'
import Timer from '../../components/preset/presA02/Timer'
import Gallery from '../../components/preset/presA02/Gallery'
import Comments from '../../components/preset/presA02/Comments'
import { FaAngleDoubleDown,FaRegEnvelopeOpen, FaInstagram, 
        FaSearchLocation, FaRegCopy, FaPause } from "react-icons/fa"
import GalleryFade from '../../components/preset/presA02/GalleryFade'


function PresA02({url}) {

    const audioRef = useRef()
    const [isPlaying, setIsPlaying] = useState(false)
    const [scrollTo, setScrollTo] = useState('opening')

    const togglePlay = () => {
        if (isPlaying) {
            audioRef.current.pause()
        } else {
            audioRef.current.play()
        }
        setIsPlaying(!isPlaying)
    };

    const router = useRouter()
    const { to } = router.query
    const [topPosition, setTopPosition] = useState(0)

    const moveUp = () => {
        setTopPosition(topPosition - 1000)
        togglePlay()
    }

    {/* TO DO: DATA GALLERY*/}
    const images = [
        { src: '/images/preset/A02/TM18-1Z.jpg', alt: 'First' },
        { src: '/images/preset/A02/TM18-2.jpg', alt: 'First' },
        { src: '/images/preset/A02/TM18-16.jpg', alt: 'First' },
        { src: '/images/preset/A02/TM18-11.jpg', alt: 'First' },
        
    ]

    const images_slide = [
        { src: '/images/preset/A02/TM18-8.jpg', alt: 'First' },
        { src: '/images/preset/A02/TM18-5.jpg', alt: 'First' },
       
        { src: '/images/preset/A02/TM18-6.jpg', alt: 'First' },
        { src: '/images/preset/A02/TM18-7.jpg', alt: 'First' },
    ]

    const scrollToTarget = (targetId) => {
       setScrollTo(targetId)
    }

    useEffect(()=>{
        const element = document.getElementById(`${scrollTo}`)
        element.scrollIntoView({behavior:'smooth'})
      },[scrollTo])

    useEffect(()=>{
        const fadeUpElements = document.querySelectorAll(".fadeUp")
        fadeUpElements.forEach((element) => {
            console.log("looped")

            gsap.set(element, {
                y: 80, 
                opacity: 0, 
            });

            ScrollTrigger.create({
                trigger: element,
                start: "top 90%", 
                toggleActions: "play", 
                animation: gsap.to(element, {
                y: 0, 
                opacity: 1,
                duration: 1, 
                ease: "power2.out",
                }),
            })
        })
    },[])


  
    return (
        <div className=' w-full box-content text-white font-Wix'>

            {/* TO DO: BACKDOUND MP3*/}
            <audio  loop ref={audioRef} src="/audio/wedding-cinematic.mp3" />
            <Head>
                {/* TO DO: TITLE PERNIKAHAN*/}
                <title>Rabine.id - Preview </title>

                <meta name="description" content="Generated by create next app" />
                <meta property="og:image" content="http://contentmanagement.cendikabangsa.sch.id/wp-content/uploads/2023/09/WhatsApp-Image-2023-09-23-at-17.04.06.jpeg" />
                <meta property="og:image:width" content="400" />
                <meta property="og:image:height" content="300" />
                <link rel="icon" href="/rbn.ico" />
                <script async src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
                <script async src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
                <script async src="https://unpkg.com/@dotlottie/player-component@latest/dist/dotlottie-player.mjs" type="module"></script> 
                <style>{`
                        ::-webkit-scrollbar {
                            width: 8px; /* Lebar scrollbar */
                          }
                          ::-webkit-scrollbar-thumb {
                            background-color: #333333; /* Warna thumb scrollbar */
                            border-radius: 6px; /* Sudut melengkung */
                          }
                    `}
                </style>
            </Head>
            <div className='w-full flex flex-row items-start justify-between'>

                {/* COVER UNDANGAN */}
                <div className='w-full h-screen fixed z-20 moving-up flex flex-col items-start justify-start' style={{ top: `${topPosition}px` }}>
                    <div className='w-full h-screen relative flex items-center justify-center '>
                        
                        <div className='flex flex-col items-center justify-end absolute bg-gradient-to-t 
                                    from-[#3c3838]/50 to-transparent w-full h-screen top-0 pb-40'>
                            <h1>THE WEDDING OF</h1>

                            {/* TO DO: NAMA KEDUA MEMPELAI*/}
                            <h1 className='font-bold text-5xl pb-8 font-Photograph-Signature'>Andre & Citra</h1>

                            <p className='text-sm'>Kepada Yth. Bapak/Ibu/Saudara(i)</p>
                            <h1 className='py-8 font-bold'>{to}</h1>
                            <button className='flex flex-row items-center justify-center gap-2 blink bg-white rounded-lg 
                                            text-black px-5 py-2 hover:bg-yellow-100' onClick={moveUp}>
                               <FaRegEnvelopeOpen/> Buka Undangan
                            </button>
                        </div>

                        {/* TO DO: GAMBAR UNTUK BACKGROUND OPENING*/}
                        <Image
                            src='/images/preset/A02/TM18-10.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                    </div>
                </div>

                {/* SISI KIRI (TAMPILAN PC) */}

                {/* TO DO: GAMBAR UNTUK SISI KIRI TAMPILAN PC*/}
                <div className="hidden lg:flex bg-cover bg-right md:w-1/2 lg:w-[60%] h-screen overflow-hidden sticky top-0" 
                     style={{backgroundImage: "url('/images/preset/A02/TM18-18.jpg')"}}>

                    <div className='gap-y-4 w-full h-full bg-gradient-to-l from-[#B6B5B9] to-transparent flex flex-col justify-end items-end 
                                 py-12 px-10 relative'>
                                    
                        <FaAngleDoubleDown className='scroll-me font-bold text-xl '/>
                        <h1>scroll ke bawah</h1>
                        <div className='w-full flex flex-row items-center justify-between'>
                            <div onClick={togglePlay} className='flex flex-row items-start cursor-pointer justify-between text-white gap-x-4'>
                                {isPlaying ? <dotlottie-player src="https://lottie.host/33f853c2-3ac1-4ca2-a738-c642fbdf8f62/5MK6jbaDeb.json" 
                                    background="transparent" 
                                    speed="1" 
                                    style={{width: 40+'px', height: 40+'px'}} 
                                    loop 
                                    autoplay>
                                </dotlottie-player> 
                                : 
                                <div className='w-[40px] h-[40px]  text-yellow-500 flex flex-col items-center justify-center'>
                                    <FaPause/>
                                </div>}
                                <div className='flex flex-col items-start justify-center text-xs '>
                                    <h1 className='font-bold'>{isPlaying ? 'Now Playing' : 'Paused'}</h1>

                                    {/* TO DO: JUDUL LAGU*/}
                                    <h1>Romantic Love - Alex P.</h1>
                                </div>
                            </div>
                            {/* TO DO: NAMA MEMPELAI*/}
                            <h1 className='text-3xl font-bold text-right font-Batusa'>The Wedding Of Andre And Citra</h1>
                        </div>
                    </div>
                </div>

                {/* SISI KANAN */}
                <div className='w-full  lg:w-[40%] overflow-y-auto relative text-[#747373]'>

                    {/* NOW PLAYING*/}
                    <div className='lg:hidden flex flex-col items-center justify-between gap-x-4 fixed w-full
                                     top-4 z-10 '>
                         <div onClick={togglePlay} className='flex flex-row items-center justify-between bg-white/45 backdrop-blur-lg rounded-full py-1 px-6 gap-x-4'>
                            {isPlaying ? <dotlottie-player src="https://lottie.host/33f853c2-3ac1-4ca2-a738-c642fbdf8f62/5MK6jbaDeb.json" 
                                background="transparent" 
                                speed="1" 
                                style={{width: 40+'px', height: 40+'px'}} 
                                loop 
                                autoplay>
                            </dotlottie-player> 
                            : 
                            <div className='w-[40px] h-[40px]  text-yellow-500 flex flex-col items-center justify-center'>
                                <FaPause/>
                            </div>}
                            <div className='flex flex-col items-start justify-center text-xs text-black'>
                                <h1 className='font-bold'>{isPlaying ? 'Now Playing' : 'Paused'}</h1>

                                {/* TO DO: JUDUL LAGU*/}
                                <h1>Romantic Love - Alex P.</h1>
                            </div>
                        </div>                    
                    </div>

                    {/* NAVIGASI MENU BAWAH */}
                    <div className='lg:hidden flex flex-row items-center justify-center w-full fixed z-10 bottom-0 py-4 bg-[#3c3838]/50 backdrop-blur-xl space-x-6 '>
                        <Image
                            src='/images/preset/A01/marriage.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('mempelai')}
                        />
                        <Image
                            src='/images/preset/A01/wedding-bells.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('jadwal')}
                        />
                          
                        <Image
                            src='/images/preset/A01/gps.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('lokasi')}
                        />
                        <Image
                            src='/images/preset/A01/photo-camera.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('gallery')}
                        />
                        <Image
                            src='/images/preset/A01/love-letter.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('opening')}
                        />
                        <Image
                            src='/images/preset/A01/wedding-gift.png'
                            width={500}
                            height={500}
                            className='w-[8%] object-contain'
                            alt='appstore'
                            onClick={()=>scrollToTarget('gift')}
                        />
                            
                   </div>

                    {/* OPENING_PHOTO */}
                   <div id='opening' className='w-full h-screen relative'>
                        <div className='p-12 absolute top-0 bg-gradient-to-t from-black/20 to-transparent w-full h-full text-white flex flex-col items-center justify-end pb-40 fadeUp'>
                            <p>THE WEDDING OF</p>

                            {/* TO DO: NAMA MEMPELAI*/}
                            <h1 className='font-bold text-6xl py-4 font-Photograph-Signature text-center'>Andre &<br/>Citra</h1>
                        
                                {/* TO DO: TANGGAL NIKAH*/}
                                <p className='text-center'>24 Mei 2024</p> 
                        </div>

                        {/* TO DO: GAMBAR OPENING*/}
                        <Image
                            src='/images/preset/A02/TM18-16.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                   </div>

                   {/* AYAT ALQUR'AN */}
                    <div className='w-full relative text-sm flex flex-col items-center justify-center px-16 py-[80px] bg-[#FFFBF4]'>
                    
                        <p className='text-center fadeUp'>
                            “Dan diantara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, 
                            agar kamu cenderung dan merasa tenteram kepadanya dan Dia menjadikan diantaramu rasa kasih dan sayang. 
                            Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.“
                        </p>
                        <p className='text-center text-lg py-4 font-bold fadeUp'>
                            (QS. Ar-Rum ayat 21)
                        </p>
                    </div>

                   {/* QUOTES CALON PENGANTEN*/}
                    <div className='w-full flex flex-col items-center justify-center bg-[#FFFBF4]'>
                        <div className='w-full h-full flex flex-row items-end justify-end'>
                        
                            {/* TO DO: ISI DATANYA*/}
                            <Image
                                src='/images/preset/A02/TM18-10.jpg'
                                width={1200}
                                height={1200}
                                className='w-3/4 object-cover rounded-l-full  fadeUp'
                                alt='appstore'
                            />
                          </div>
                        <p className='text-center p-10 fadeUp text-sm'>
                            We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly.
                        </p>
                        <div className='w-full h-full flex flex-row items-start justify-start'>
                        
                            {/* TO DO: ISI DATANYA*/}
                            <Image
                                src='/images/preset/A02/TM18-9.jpg'
                                width={1200}
                                height={1200}
                                className='w-3/4 object-cover rounded-r-full  fadeUp'
                                alt='appstore'
                            />
                      </div>
                    </div>

                     {/* MEMPELAI */}
                    <div id='mempelai' className='w-full relative bg-center bg-cover flex flex-col text-sm items-center justify-center 
                                                    px-16 py-[100px] text-center bg-[#FFFBF4]'>
                         <Image
                                src='/images/preset/A02/TM18-1.png'
                                width={1200}
                                height={1200}
                                className='w-2/4 object-cover rounded-[40px] fadeUp'
                                alt='appstore'
                            />

                        {/* TO DO: ISI DATANYA*/}
                        <h1 className='font-bold text-2xl font-DMSerif py-6 fadeUp text-[#3c3838]'>Citra Lestari Alamku</h1>
                        {/* TO DO: ISI DATANYA*/}
                        <h1 className='my-8 fadeUp'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center fadeUp text-[#3c3838]'>
                            <FaInstagram/>
                            citra_la
                        </div>
                        <h1 className='text-[5rem] my-20 font-Royal-Exq text-[#3c3838] fadeUp'>&</h1>
                  
                         <Image
                                src='/images/preset/A02/TM18-2.png'
                                width={1200}
                                height={1200}
                                className='w-2/4 object-cover rounded-[40px] fadeUp'
                                alt='appstore'
                            />
                        <h1 className='font-bold text-2xl font-DMSerif py-6 fadeUp text-[#3c3838]'>Andre Taulanu</h1>
                        <h1 className='my-8 fadeUp'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center fadeUp text-[#3c3838]'>
                            <FaInstagram/>
                            andre_t
                        </div>
                    </div>

                    {/* INFO ACARA */}
                    <div id='jadwal' className='w-full  relative bg-center bg-cover ' 
                        style={{backgroundImage: "url('/images/preset/A02/TM18-1Z.jpg')"}}>
                        <div className='w-full  flex flex-col items-center bg-white/40 justify-center text-[#151313] p-8 space-y-6 '>
                            <div className='bg-white/40 rounded-xl p-8 space-y-4 shadow-xl backdrop-blur-sm fadeUp'>
                                <div className='flex flex-col items-center justify-center text-center gap-y-2'>
                                    <h1 className='text-3xl font-DMSerif fadeUp mb-6 fadeUp'>Akad Nikah</h1>
                                    <h1 className='text-sm fadeUp'>Minggu 10 Mei 2024</h1>
                                    <h1 className='text-sm fadeUp'>09.00 - 11.00 WIB</h1>
                                    <h1 className='text-xl font-DMSerif fadeUp mt-4 fadeUp'>Hotel Grand Orchard</h1>
                                    <h1 className='text-sm fadeUp'>Gunung Sahari - Kemayoran Jakarta pusat</h1>
                                    <button className='text-white fadeUp flex flex-row items-center justify-center text-sm rounded-lg  gap-2 border bg-[#151313] border-white px-3 py-2 mt-8
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out fadeUp'>
                                        <FaSearchLocation/> view Location
                                    </button>
                                </div>
                            </div>
                            <div className='bg-white/40 rounded-xl p-8 space-y-4 shadow-xl backdrop-blur-sm fadeUp'>
                                <div className='flex flex-col items-center justify-center text-center gap-y-2'>
                                    <h1 className='text-3xl font-DMSerif fadeUp mb-6 fadeUp'>Resepsi</h1>
                                    <h1 className='text-sm fadeUp'>Minggu 10 Mei 2024</h1>
                                    <h1 className='text-sm fadeUp'>09.00 - 11.00 WIB</h1>
                                    <h1 className='text-xl font-DMSerif fadeUp mt-4 fadeUp'>Hotel Grand Orchard</h1>
                                    <h1 className='text-sm fadeUp'>Gunung Sahari - Kemayoran Jakarta pusat</h1>
                                    <button className='text-white fadeUp flex flex-row items-center justify-center text-sm rounded-lg  gap-2 border bg-[#151313] border-white px-3 py-2 mt-8
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out fadeUp'>
                                        <FaSearchLocation/> view Location
                                    </button>
                                </div>
                            </div>
                          
                        </div>
                    </div>

                     {/* GOOGLE MAP */}
                     <div id='lokasi' className='w-full flex flex-col items-center justify-center gap-y-8 bg-[#FFFBF4] p-4'>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15799.40307219353!2d112.5761332!3d-8.1166731!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e789fe408c2880b%3A0x60b0af7bd09faf32!2snadhirdecal!5e0!3m2!1sid!2sid!4v1708078149410!5m2!1sid!2sid" 
                                className='w-full h-[500px] rounded-xl'
                                width="600" 
                                    height="600" 
                                    style={{border:0}} 
                                    allowFullScreen="" 
                                    loading="lazy" 
                                    referrerPolicy="no-referrer-when-downgrade">
                        </iframe>
                    </div>

                    {/* COUNTDOWN */}
                    <Timer targetDate = {'2024-02-24T08:00:00Z'} anim = {{fadeUp :'fadeUp'}}/>

                    <Gallery id={'gallery'} images={images}/>

                    {/* YOUTUBE */}
                    <div className='w-full flex flex-col items-center justify-center px-4  gap-y-8 py-20 bg-[#FFFBF4] '>
                        <iframe 
                            className='w-full fadeUp rounded-xl'
                            height="315" 
                            src="https://www.youtube-nocookie.com/embed/kebq86BTZFA?si=9saOo4u4j5ry06DO" 
                            title="YouTube video player" 
                          
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                            allowFullScreen>
                        </iframe>
                    </div>

                    <Comments slug={'presA02'} url={url} tamu={to}/>

                    <GalleryFade images={images_slide}/>

                    {/* GIFT */}
                    <div id='gift' className='h-full  py-12 flex gap-y-8 flex-col items-center justify-center text-[#151313]'  >
                    <h1 className='text-3xl font-DMSerif fadeUp mb-6 fadeUp'>Gift</h1>
                           <div className='w-[400px] flex rounded-lg p-8 bg-cover bg-center flex-col items-start justify-between fadeUp' 
                                style={{backgroundImage: "url('/images/preset/A02/card-bg.jpg')"}}>
                               <div className='flex flex-row items-center justify-between w-full'>
                                    <h1>Mandiri</h1>
                                    <Image
                                        src='/images/preset/A01/mandiri.webp'
                                        width={1000}
                                        height={1000}
                                        className='w-[28%] object-contain'
                                        alt='appstore'
                                    />
                               </div>
                               <Image
                                    src='/images/preset/A01/chip.png'
                                    width={1000}
                                    height={1000}
                                    className='w-[12%] object-contain my-8'
                                    alt='appstore'
                                />
                                <h1 className=' text-[1rem] text-center tracking-wider font-GameCube mb-4'>647387374648</h1>
                                <h1>Andre T</h1>
                           </div>
                           <button className='text-white fadeUp flex flex-row items-center justify-center text-sm rounded-lg  gap-2 border bg-[#151313] border-white px-3 py-2 mt-8
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out fadeUp'>
                            <FaRegCopy/> copy no rek
                        </button>
                           <div className='w-[400px] flex rounded-lg p-8 bg-cover bg-center flex-col items-start justify-between fadeUp' 
                                style={{backgroundImage: "url('/images/preset/A02/card-bg.jpg')"}}>
                               <div className='flex flex-row items-center justify-between w-full'>
                                    <h1>BCA</h1>
                                    <Image
                                        src='/images/preset/global/BCA.webp'
                                        width={1000}
                                        height={1000}
                                        className='w-[28%] object-contain'
                                        alt='appstore'
                                    />
                               </div>
                               <Image
                                    src='/images/preset/A01/chip.png'
                                    width={1000}
                                    height={1000}
                                    className='w-[12%] object-contain my-8'
                                    alt='appstore'
                                />
                                <h1 className=' text-[1rem] text-center tracking-wider font-GameCube mb-4'>647387374648</h1>
                                <h1>Citra ALamaku</h1>
                           </div>
                           <button className='text-white fadeUp flex flex-row items-center justify-center text-sm rounded-lg  gap-2 border bg-[#151313] border-white px-3 py-2 mt-8
                                        hover:bg-white hover:text-black hover:scale-105 transition-all ease-out fadeUp'>
                            <FaRegCopy/> copy no rek
                        </button>
                    </div>

                    {/* CLOSING */}
                    <div className='w-full  relative text-center h-[500px]'>
                        <div className='p-12 absolute top-0 bg-black/40 w-full h-full flex flex-col items-center justify-end text-white'>
                            <p className='text-sm'>Two souls become one, two hearts beat as one</p>
                            <h1 className='font-bold text-3xl py-4 font-Photograph-Signature'>Andre & Citra</h1>
                           
                                <p className='w-1/3'>Thank You</p>
                           
                            
                        </div>
                        <Image
                            src='/images/preset/A02/TM18-3.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                   </div>

                   {/* WATERMARK */}
                   <div className='w-full bg-black flex flex-col items-center text-slate-400 justify-center gap-y-1 text-xs text-center pt-10 pb-20 lg:pb-10'>
                        <h1>made with love and passion by</h1>
                        <h1 className='text-base font-bold'>Rabine</h1>
                        <h1>ingin punya undangan keren seperti ini?<br/> Hubungi kami sekarang juga</h1>
                        <h1>copyright rabine 2024</h1>
                   </div>
                </div>
            </div>
        </div>
    )
}
export async function getServerSideProps() {
    const url = process.env.API_URL_PROD
    return { props: {url} }
}

export default PresA02
