import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useRouter } from 'next/router'
import { useState} from 'react'
import Timer from '../../components/preset/presA01/Timer'
import { FaAngleDoubleDown,FaRegEnvelopeOpen, FaInstagram, FaSearchLocation } from "react-icons/fa"


function PresA01() {

    const router = useRouter()
    const { to } = router.query

    const [topPosition, setTopPosition] = useState(0)

    const moveUp = () => {
        setTopPosition(topPosition - 1000);
    }


  
    return (
        <div className=' w-full box-content text-white'>
            <Head>
                <title>Rabine.id - Preview </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/rbn.ico" />
            </Head>
            <div className='w-full flex flex-row items-start justify-between'>

                {/* COVER UNDANGAN */}
                <div className='w-full h-screen fixed z-10 moving-up flex flex-col items-center justify-center' style={{ top: `${topPosition}px` }}>
                    <div className='w-full h-screen relative flex items-center justify-center'>
                        <div className='flex flex-col items-center justify-end absolute bg-gradient-to-t from-black 
                                        to-transparent via-black/75 w-full h-screen top-0 pb-20'>
                            <h1>THE WEDDING OF</h1>
                            <h1 className='font-bold text-5xl pb-8 '>ANDRE & CITRA</h1>
                            <p className='text-sm'>Kepada Yth. Bapak/Ibu/Saudara(i)</p>
                            <h1 className='py-8 font-bold'>{to}</h1>
                            <button className='flex flex-row items-center justify-center gap-2 blink bg-white rounded-lg 
                                            text-black px-5 py-2 hover:bg-yellow-100' onClick={moveUp}>
                               <FaRegEnvelopeOpen/> Buka Undangan
                            </button>
                        </div>
                        <Image
                            src='/img/preset/A01/bg-couple.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                    </div>
                </div>

                {/* SISI KIRI (TAMPILAN PC) */}
                <div className="hidden md:flex bg-cover bg-center md:w-1/2 lg:w-[60%] h-screen overflow-hidden sticky top-0 " 
                     style={{backgroundImage: "url('/img/preset/A01/bg-couple.jpg')"}}>
                    <div className='gap-y-4 w-full h-full bg-gradient-to-l from-black to-transparent flex flex-col justify-end items-end 
                                 py-12 px-10'>
                    <FaAngleDoubleDown className='scroll-me font-bold text-xl '/>
                        <h1>scroll ke bawah</h1>
                        <h1 className='text-3xl font-bold text-right font-Batusa'>The Wedding Of Randy And Citra</h1>
                    </div>
                </div>

                {/* SISI KANAN */}
                <div className='w-full md:w-1/2 lg:w-[40%] overflow-y-auto'>

                    {/* OPENING_PHOTO */}
                   <div className='w-full h-screen relative'>
                        <div className='p-12 absolute top-0 bg-black/40 w-full h-full flex flex-col items-start justify-end'>
                            <p>THE WEDDING OF</p>
                            <h1 className='font-bold text-6xl py-4 font-Royal-Exq'>ANDRE &<br/>CITRA</h1>
                            <div className='flex flex-row items-end justify-start w-full'>
                                <p className='tracking-[0.5rem]'>24.05.2024</p>
                                <div className='w-full h-[1px] bg-white'></div>
                            </div>
                        </div>
                        <Image
                            src='/img/preset/A01/couple-opening.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                   </div>

                   {/* AYAT ALQUR'AN */}
                    <div className='w-full relative bg-center bg-cover flex flex-col items-center justify-center px-16 py-[200px]'
                         style={{backgroundImage: "url('/img/preset/A01/Template-1-Marble.webp')"}}>
                         <Image
                            src='/img/preset/A01/separator-saphire.svg'
                                width={1200}
                                height={1200}
                                className='w-[5%] absolute top-10'
                                alt='appstore'
                        />
                         <Image
                            src='/img/preset/A01/separator-saphire.svg'
                                width={1200}
                                height={1200}
                                className='w-[5%] absolute bottom-28'
                                alt='appstore'
                        />
                        <p className='text-center'>
                            “Dan diantara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, 
                            agar kamu cenderung dan merasa tenteram kepadanya dan Dia menjadikan diantaramu rasa kasih dan sayang. 
                            Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir.“
                        </p>
                        <p className='text-center text-xl py-4'>
                            (QS. Ar-Rum ayat 21)
                        </p>
                    </div>

                   {/* QUOTES CALON PENGANTEN*/}
                     <div className='w-full  relative'>
                        <div className='p-12 absolute top-0 bg-black/80 w-full h-full flex flex-col items-center justify-between'>
                        <Image
                            src='/img/preset/A01/bg-couple.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover rounded-xl -mt-28'
                            alt='appstore'
                        />
                        <p className='text-center font-bold text-xl lg:text-3xl px-10 lg:px-28'>
                            Love seems the swiftest but it is the slowest of all growths. No man or woman really knows what perfect 
                            love is until they have been married a quarter of a century.
                        </p>
                        <Image
                            src='/img/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%]'
                            alt='appstore'
                        />
                        </div>
                        <Image
                            src='/img/preset/A01/bg-section-1.jpg'
                            width={1200}
                            height={1200}
                            className='w-full object-cover h-full'
                            alt='appstore'
                        />
                    </div>

                     {/* MEMPELAI */}
                     <div className='w-full relative bg-center bg-cover flex flex-col items-center justify-center px-16 py-[100px] text-center'
                        style={{backgroundImage: "url('/img/preset/A01/Template-1-Marble.webp')"}}>
                        <div className='w-[14rem] h-[16rem] rounded-t-full bg-top bg-cover'  style={{backgroundImage: "url('/img/preset/A01/bride.png')"}}></div>
                        <h1 className='font-bold text-2xl font-Royal-Exq'>Citra Lestari Alamku</h1>
                        <Image
                            src='/img/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%] my-6'
                            alt='appstore'
                        />
                        <h1 className='my-8'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center'>
                            <FaInstagram/>
                            citra_la
                        </div>
                        <h1 className='text-[5rem] my-10 font-Royal-Exq'>&</h1>
                        <div className='w-[14rem] h-[16rem] rounded-t-full bg-top bg-cover'  style={{backgroundImage: "url('/img/preset/A01/groom.png')"}}></div>
                        <h1 className='font-bold text-2xl font-Royal-Exq'>Andre Taulanu</h1>
                        <Image
                            src='/img/preset/A01/separator-sparkling.svg'
                            width={1200}
                            height={1200}
                            className='object-cover w-[8%] my-6'
                            alt='appstore'
                        />
                        <h1 className='my-8'>Putri dari <br/> Bapak Budi Mulyanto <br/> Dan Ibu Pangastuti R</h1>
                        <div className='flex gap-2 text-sm items-center justify-center'>
                            <FaInstagram/>
                            citra_la
                        </div>
                    </div>

                    {/* INFO ACARA */}
                    <div className='w-full  relative bg-center bg-cover ' style={{backgroundImage: "url('/img/preset/A01/bg-section-2.jpg')"}}>
                        <div className='bg-gradient-to-t from-black to-black/50 via-black/80 w-full h-full  flex flex-col items-center justify-center
                                        py-20 px-12 gap-y-10 text-center'>
                            <div className='flex flex-col items-center justify-center'>
                                <h1 className='text-2xl font-Royal-Exq'>Minggu, 24 Mei 2024</h1>
                                <Image
                                    src='/img/preset/A01/separator-sparkling.svg'
                                    width={1200}
                                    height={1200}
                                    className='object-cover w-[20%]'
                                    alt='appstore'
                                />
                            </div>
                            <div className='flex flex-col items-center justify-center'>
                                <h1 className='text-3xl font-Royal-Exq'>Akad Nikah</h1>
                                <p>08.00 WIB s/d Selesai</p>
                            </div>
                            <div className='flex flex-col items-center justify-center'>
                                <h1 className='text-3xl font-Royal-Exq'>Resepsi Pernikahan</h1>
                                <p>10.00 WIB s/d Selesai</p>
                            </div>
                            <div className='flex flex-col items-center justify-center'>
                                <h1 className='text-3xl font-Royal-Exq'>Hotel Jayakarta Bandung</h1>
                                <p>Jl. Ir. Juanda No 381A, Dago, Kecamatan Coblong, Kota Bandung, Jawa Barat</p>
                            </div>

                            <button className='flex flex-row items-center justify-center gap-2 border border-white px-5 py-2
                                            hover:bg-white hover:text-black hover:scale-105 transition-all ease-out'>
                                <FaSearchLocation/> view Location
                            </button>
                           
                        </div>
                    </div>
                    <div className='w-full flex flex-col items-center justify-center'>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15799.40307219353!2d112.5761332!3d-8.1166731!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e789fe408c2880b%3A0x60b0af7bd09faf32!2snadhirdecal!5e0!3m2!1sid!2sid!4v1708078149410!5m2!1sid!2sid" 
                               className='w-full h-[500px]'
                               width="600" 
                                height="600" 
                                style={{border:0}} 
                                allowfullscreen="" 
                                loading="lazy" 
                                referrerpolicy="no-referrer-when-downgrade">
                    </iframe>
                   
                    </div>
                    <Timer/>
                </div>
            </div>
        </div>
    )
}

export default PresA01
