import Head from 'next/head'
import Beralih from '../components/index/Beralih'
import Features from '../components/index/Features'
import Hero from '../components/index/Hero'
import LatestProd from '../components/index/LatestProd'
import Navbar from '../components/index/Navbar'
import Pricing from '../components/index/Pricing'
import SampleProduct from '../components/index/SampleProduct'
import fitur from'../source/dataFitur.json'
import BlogFeed from '../components/index/BlogFeed'
import { useRecoilState } from 'recoil'
import { navState } from '../recoil/navState'
import { useEffect } from 'react'
import { motion } from 'framer-motion'
import Footer from '../components/globals/Footer'
import axios from 'axios';
require('dotenv').config();





function Home({fitur,dataApi,dataLatest}) {

  const [menuActive,setMenuActive] = useRecoilState(navState)
  const intersect='20vw'
  const duration = 0.4
  const style = 'easeOut'

  useEffect(()=>{
    const element = document.getElementById(`content${menuActive}`)
    element.scrollIntoView({behavior:'smooth'})
  
  },[menuActive])

  return (
    <div className='w-full base '>
      <Head>
        <title>Rabine.id - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rbn.ico" />
      </Head>
      <Navbar />
      <main className='w-full mx-auto px-6 md:px-12 max-w-[1200px]'>
        <Hero id={1} />
        <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:style}}
          >
          <Beralih id={2}/>
        </motion.div>
        <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:'circOut'}}
        >
          <Features/>
        </motion.div>
        <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:style}}
        >
        <Pricing id={3} fitur={fitur}/>
        </motion.div>
      </main>
      <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:style}}
        >
      <LatestProd data={dataLatest.undangan}/>
      </motion.div>
      <main className='w-full mx-auto  md:px-12 max-w-[1300px]'>
      <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:style}}
        >
        <SampleProduct data={dataApi.undangan} id={5}/>
        </motion.div>
      </main>
      <motion.div
            initial={{ opacity: 0,y:intersect }}
            whileInView={{ opacity: 1,y:0 }}
            viewport={{ once: true }}
            transition={{duration:duration,ease:style}}
        >
      <BlogFeed id={6}/>
      </motion.div>
    <Footer/>
    </div>
  )
}


export async function getServerSideProps() {

  const url = `${process.env.API_URL_PROD}`
  const res = await fetch(url+'product/', {
    headers: {
      Authorization: 'Bearer XXUiop67RTfr45GTJU90CFR'
    }
  })
  const latest = await fetch(url+'product/latest', {
    headers: {
      Authorization: 'Bearer XXUiop67RTfr45GTJU90CFR'
    }
  })
  const dataApi = await res.json()
  const dataLatest = await latest.json()

  return { props: { dataApi,fitur,dataLatest } }
}

export default Home;
