import Head from 'next/head'
import Beralih from '../components/index/Beralih'
import Features from '../components/index/Features'
import Hero from '../components/index/Hero'
import LatestProd from '../components/index/LatestProd'
import Navbar from '../components/index/Navbar'
import Pricing from '../components/index/Pricing'
import SampleProduct from '../components/index/SampleProduct'
import data from '../source/dataUndangan.json'
import fitur from'../source/dataFitur.json'
import BlogFeed from '../components/index/BlogFeed'
import { useRecoilState } from 'recoil'
import { navState } from '../recoil/navState'
import { useEffect } from 'react'




function Home({undangan,fitur}) {

  const [menuActive,setMenuActive] = useRecoilState(navState)

  useEffect(()=>{
    const element = document.getElementById(`content${menuActive}`)
    element.scrollIntoView({behavior:'smooth'})
    console.log(menuActive);
  },[menuActive])

  return (
    <div className='w-full base '>
      <Head>
        <title>Rabine.id - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rbn.ico" />
      </Head>
      <Navbar />
      <main className='w-full mx-auto px-6 md:px-12 max-w-[1200px]'>
        <Hero id={1} />
        <Beralih id={2}/>
        <Features/>
        <Pricing id={3} fitur={fitur}/>
      </main>
      <LatestProd data={undangan}/>
      <main className='w-full mx-auto  md:px-12 max-w-[1300px]'>
        <SampleProduct data={undangan} id={5}/>
      </main>
      <BlogFeed id={6}/>
   
    </div>
  )
}

Home.getInitialProps = async () => {
  
  return { undangan: data.undangan,fitur }
}

export default Home;
