import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

function presA01() {
  return (
    <div className=' w-full'>
        <Head>
            <title>Rabine.id - Preview </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/rbn.ico" />
        </Head>
        <div className=''>
            <div className='max-w-[600px] mx-auto relative'>
                <Image
                    src='/presA01/cover_inner.png'
                    width={2000}
                    height={2000}
                    alt='woman Rabine.id'
                    style={{objectFit:`cover`}}
                    className='absolute -z-10 top-0 '
                />

            <h1 className='text-center'>The Wedding Of</h1>
            <div className='flex flex-col items-center justify-center gap-y-3 pt-[50%]'>
                
            </div>
            </div>
            
         
        </div>
    </div>
  )
}

export default presA01