import { useRouter } from 'next/router'
import React from 'react'
import Head from 'next/head'
import NavbarSecond from '../../components/globals/NavbarSecond'
import Footer from '../../components/globals/Footer'
import DetailPreset from '../../components/product_detail/DetailPreset'

function ProdId({preset}) {

    const router = useRouter()
    const {presetId} = router.query
    const detailData = preset.undangan[0]
  return (

    <div className='w-full base '>
      <Head>
        <title>Rabine.id - Lihat Preset Desain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rbn.ico" />
      </Head>
      <NavbarSecond />
      <main className='w-full mx-auto px-6 md:px-12 max-w-[1200px]'>
        
        <DetailPreset idPreset={presetId} namePreset={detailData.title} catPreset={detailData.category} imgPreset={detailData.img} priceP={25000} tagPreset={["elegant","rustic","minimalist","grey"]}/>
     </main>
     <Footer/>
    </div>

  )
}

export async function getServerSideProps(context) {

  const {id} = context.params
  const res = await fetch(`http://apirabine.cendikabangsa.sch.id/product/id/${id}`)
  const preset = await res.json()

  return { props: {preset} }
}


export default ProdId