import { useRouter } from 'next/router'
import React from 'react'
import data from '../../source/dataUndangan.json'
import price from '../../source/dataFitur.json'
import Head from 'next/head'
import NavbarSecond from '../../components/globals/NavbarSecond'
import DetailPreset from '../../components/product_detail/DeatilPreset'


function prodId({undangan,price}) {

    const router = useRouter()
    const {presetId} = router.query
    const selected = undangan.filter(item => item.id === presetId )[0];
    let pricePreset
   if(selected.kategori === 'basic'){
      pricePreset = price.basic.price
   }else{
      pricePreset = price.premium.price
   }

  return (

    <div className='w-full base '>
      <Head>
        <title>Rabine.id - Lihat Preset Desain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rbn.ico" />
      </Head>
      <NavbarSecond />
      <main className='w-full mx-auto px-6 md:px-12 max-w-[1200px]'>
        <DetailPreset idPreset={selected.id} namePreset={selected.nama} catPreset={selected.kategori} imgPreset={selected.img} priceP={pricePreset} />
     </main>
    </div>

  )
}

prodId.getInitialProps = async () => {
    return { undangan: data.undangan, price:price.paket }
  }
export default prodId