import { useRouter } from 'next/router'
import React from 'react'
import Head from 'next/head'
import NavbarSecond from '../../components/globals/NavbarSecond'
import Footer from '../../components/globals/Footer'
import DetailPreset from '../../components/product_detail/DetailPreset'

function ProdId({preset}) {

    const router = useRouter()
    const {presetId} = router.query
    const detailData = preset.undangan[0]
    console.log(preset);

  return (
    <div className='w-full base '>
      <Head>
        <title>Rabine.id - Lihat Preset Desain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/rbn.ico" />
      </Head>
      <NavbarSecond />
      <main className='w-full mx-auto px-6 md:px-12 max-w-[1200px]'>
        <DetailPreset idPreset={detailData.Product_Id} 
        namePreset={detailData.Product_Name} 
        catPreset={detailData.Product_Category} 
        imgPreset={detailData.Product_Img} 
        priceP={25000}
        slug={detailData.Product_Slug} />
     </main>
     <Footer/>
    </div>
  )
}

export async function getServerSideProps(context) {

  const { id } = context.params;

  //fetch detail preset by id
  const url = `${process.env.API_URL_PROD}`
  const res = await fetch(url+`product/slug/${id}`, {
    headers: {
      Authorization: 'Bearer XXUiop67RTfr45GTJU90CFR' 
    }
  })
  const preset = await res.json()
  console.log(url);

  return { props: {preset} }
}





export default ProdId